### ISSUE TITLE
2024-03-21 Ichnotaxonomy

### ISSUE THREAD

**Issue by ekrimmel** [paleo-data/happy-hours#43]
## Checklist for hosting a PDWG Happy Hour 

**Is this happy hour related to any [topic idea issues](https://github.com/paleo-data/happy-hours/labels/idea)?** If so, please link to issue(s) here: #6

### A month or more in advance
- [x] Determine topic (i.e. title of this issue)
- [x] Update topic on our [GitHub website here](https://github.com/paleo-data/paleo-data.github.io/blob/main/happy-hours.md)
- [x] Create a Google Doc for shared notes in the appropriate folder of the [PDWG Google Drive](https://drive.google.com/drive/folders/1UYyaRMMnQbgE_2FSiTdb4nLV8BAjyBz5?usp=sharing), e.g. 2024 Paleo Happy Hour Notes Recordings, using the naming convention of _YYYYMMDD_paleo-happy-hour_notes_, e.g. “20240111_paleo-happy-hour_notes”
    - To create a new shared notes doc by copying one from a previous Happy Hour, go to _File > Make a copy_ from within the previous Google Doc, then rename the new document
    - Make sure that _Sharing_ is set to “Anyone on the internet with the link can edit”

### A couple weeks in advance
- [x] Prepare for the topic by creating presentation or activity materials, if necessary, and/or by coordinating with guest speakers

### The week of
- [x] Create a Zoom link for the Happy Hour meeting
- [x] Send out a reminder email to paleo-data@googlegroups.com including details about (at least) the Happy Hour date, time, topic, and Zoom link
    - Example email subject: "Thursday 5/17 at noon Eastern - Paleo Data ‘Happy Hour’”
    - Example email text: “Please join us for the next biweekly Paleo Data Happy Hour on Thursday, May 17th at 12pm Eastern (UTC-5). The Zoom link for this meeting will be: _[insert link]_. Our theme for informal discussion this week is a working session for identifiers. In December 2020, Holly Little led a Happy Hour overview of where and why we might want to be using unique identifiers in our collections data. If you have time, reviewing the recording, notes, and/or slides _[include links]_ from that may be useful preparation for this Happy Hour, in which we will be focusing on specific identifiers (e.g. Wikidata QIDs, WoRMS AphiaIDs, Macrostrat IDs, etc.) that work best for specific types of data (e.g. people, taxa, stratigraphic units, etc.)."
- [x] Post a version of the reminder email to the _#general_ channel on our [Paleo Data Slack](https://paleo-data.slack.com/home)

### The day of the scheduled Happy Hour
- [x] Launch Zoom at least 5 minutes prior to the scheduled meeting time so that you can confirm Zoom is working as expected
- [x] At the scheduled start time, welcome everyone and let them know the meeting will be recorded
- [x] _(Alex)_ Begin recording
- [x] Lead or otherwise facilitate the progress of the Happy Hour, including introducing speakers (if appropriate), sharing the link to the notes document, moderating conversation, and closing the meeting on time
- [x] _(Alex)_ Cross check Happy Hour attendance between the shared notes self-reported attendance and Zoom; update the shared notes as needed
    - If necessary, after the meeting ends you can find the attendance report in your Zoom account online, go to _Reports > Usage_ then select the date of the Zoom meeting and look for a column called _Participants_

### After the scheduled Happy Hour
- [x] _(Alex)_ Make the recording available by downloading an MP4 file from Zoom and uploading it to the appropriate folder of the [PDWG Google Drive](https://drive.google.com/drive/folders/1UYyaRMMnQbgE_2FSiTdb4nLV8BAjyBz5?usp=sharing), e.g. 2024 Paleo Happy Hour Notes Recordings, using the naming convention of _YYYYMMDD_paleo-happy-hour_recording_, e.g. “20240111_paleo-happy-hour_recording”
- [x] _(Alex)_ Update the topic on our [GitHub website here](https://github.com/paleo-data/paleo-data.github.io/blob/main/happy-hours.md) by adding a link to the recording and by moving the topic down into the relevant section, e.g. from “2024 – Upcoming” to “2024 – Past”
- [x] _(Alex)_ On the shared notes Google Doc, change the _Sharing_ setting to “Anyone on the internet with the link can view” to better protect the document from unintentional editing in the future
- [x] Coordinate any followup from the Happy Hour as necessary, e.g. making progress on group action items, or thanking guest speakers
- [x] Close this issue

**Comment by javanveldhuizen** [comment]
Dr. Nic (Nicholas) Minter is available to be a guest speaker to talk about ichnotaxonomy. He is available after the week beginning February 26th. So, this happy hour would be good. Nic is a researcher at the School of the Environment, Geography, and Geosciences at the University of Portsmouth. He is currently working on rewriting the invert treatise on ichnofossils. Email is nic.minter@port.ac.uk. University homepage: https://www.port.ac.uk/about-us/structure-and-governance/our-people/our-staff/nic-minter.

Shall we schedule a Zoom meeting with Nic prior to this date to kind of go over what we are looking for? Other admin related stuff?

**Comment by javanveldhuizen** [comment]
Here is my email to Nic on 1/25: I am writing today to see if you would be interested in giving a presentation to our Paleo Data Working Group. There are several of us that have ichnofossils in our collection and we could use some perspectives on how we can best manage the data in our databases and sharing that data out to various data aggregators. This is especially true for ichnotaxonomy, as none of us really have a firm grasp on how it works, how it relates to normal Linnean taxonomy, how many levels in ichnotaxonomy there truly are (top level is the family?), and is there a separate system for vertebrates vs. invertebrates. Since you are redoing the ichnotaxonomy treatise, we think your expertise would be valuable here. Maybe even go into what you are doing with the treatise? Would this be something you (and maybe some colleagues?) be interested in doing? We are looking at a late February (22nd) to early March date (7th). Let me know what you think or if you have any questions.

**Comment by javanveldhuizen** [comment]
Nic's reply to my email on 1/26: Great to hear from you. Yes, that is something that I'd be interested in talking to the group about. I've been involved with some of the Workshops on Ichnotaxonomy over the years and resulting publications - so I can give an overview of ichnotaxonomy and it's complexities and nuances! I can stitch together some slides from other presentations that I've given over the years - but a Q&A would probably be useful too. The week beginning the 26th of February would probably work best for me.

**Comment by ekrimmel** [comment]
@javanveldhuizen is going to schedule a time for us to check in with Nic pre happy hour

**Comment by javanveldhuizen** [comment]
@ekrimmel Nic needs to push this back to the happy hour on the 21st. He forgot he had some other meetings scheduled for the 7. Is this cool?

**Comment by ekrimmel** [comment]
Yep, 21st works fine!

**Comment by javanveldhuizen** [comment]
@ekrimmel @tkarim @hollyel Nic would like to get together the Thursday prior to this (3/14) at our regular happy hour time (12pm eastern) to go over what we are asking of him and to answer any questions he may have. Is this date and time doable for each of you?

**Comment by ekrimmel** [comment]
Works for me!

**Comment by tkarim** [comment]
Also works for me.

**Comment by javanveldhuizen** [comment]
Sent to Nic on 3/4

Only one other happy hour on ichnotaxonomy/trace fossils/ichnofossils: 2021-08-26 (https://paleo-data.github.io/happy-hours). It was talked about having another one in November 2021, but it didn't happen. Questions/issue raised in that happy hour:
- There seems to be two ways collections record ichnotaxonomy, ichnology based and tracemaker based. Is there a preferred method? Combination of both? Neither of these?
- Does ichnotaxonomy have higher ranks above ichnogenus? If so, what are they? If not, how should collections record data in the higher ranks (family, order, class, etc.)? Leave blank, incerte sedis, indet, etc.? Put in the taxonomy of the tracemaker (see next question)?
- Should there be two separate taxonomy fields in the database, one for the ichnotaxonomy and one for the tracemaker taxonomy? Or should they be combined into one field, where the ichnotaxonomy is linked to the tracemaker taxonomy? Or does tracemaker taxonomy not matter? If the tracemaker taxonomy is relevant, how do you then deal with a trace fossils that could have been left by multiple tracemakers?
- Any thoughts on how we should share ichonotaxonomy with data aggregators (GBIF, iDigBio, etc)? Should we ask for ichnogenus and ichnospecies fields? Keep reporting it in the traditional genus and species fields? Put the names in the verbatim fields?
- Is there an ichnotaxonomy authority source that is preferred? PBDB? IRMNG? Treatise? Other website? No good source? Combination of a couple?

Other Questions (that would be good to go over if there is time)
- What other ichnofossil data should we be capturing in the database? Or what terms should we be using to make our data more discoverable? Trace type? Original vs. Cast? Original still in the field (still in situ)? Morphology? Relationships? Images?
- How should we record trace fossil interactions in our databases? For example, how should insect leaf damage be recorded? The record is identified as the leaf or the ichnotaxonomy of the leaf damage type? See the 2021-08-26 happy hour for more about interactions. Might be too big of a topic to go over in this happy hour.
