### ISSUE TITLE
Paleo Extended Specimen

### ISSUE THREAD

**Issue by ekrimmel** [paleo-data/happy-hours#5]
## What is your idea for a happy hour topic?
Possibly a two-part happy hour, consisting of (1) something akin to the [DES symposium](https://symbiota.org/des-workshop-report/) that @ljwalker & co did for Digital Data 2023, but tailored to paleo, and (2) a brainstorming session where PDWG discusses components of the ideal Paleo Extended Specimen. The latter ties into GEO OSE plans to draft an idealized data model for paleo specimens.

## Who could be involved in leading this happy hour?
@ljwalker?

## Are there any timing considerations?
Possibly could do in early 2024 (Feb 8, Feb 22, or Mar 7)

## Next steps
This issue captures a happy hour topic idea. Once you are ready to finalize an idea and put it on the PDWG happy hour schedule, please create a new issue using the [Plan a happy hour](https://github.com/paleo-data/happy-hours/issues/new?assignees=&labels=PDWG&projects=&template=plan-happy-hour.md&title=%5Breplace+this+text+with+the+happy+hour+topic%5D) template. **Then, close this issue.**

**Comment by ekrimmel** [comment]
Assigning this to Lindsay to think about and either schedule, or refine and leave off the schedule for now.

**Comment by ljwalker** [comment]
Talia and Lindsay have discussed and determined this will be presented as the Happy Hour on February 8, 2024.
